# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r


addons:
  apt:
    packages:
    - libcurl4-openssl-dev
    - libgsl0-dev
before_install:
  - cd rpackage
language: R
sudo: false
cache: packages
r_binary_packages:
  - gsl

# to stop warnings because of missing manuals
warnings_are_errors: false
# alternative is
# env:
#   global:
#     - WARNINGS_ARE_ERRORS=1
#     - R_BUILD_ARGS=--no-manual
#     - R_CHECK_ARGS=--no-manual --as-cran
# alternative is