# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

before_install:
  - cd code
addons:
  apt:
    packages:
    - libcurl4-openssl-dev
language: R
sudo: false
cache: packages