# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

addons:
  apt:
    packages:
    - libcurl4-openssl-dev
    - libgsl0-dev
before_install:
  - cd code
language: R
sudo: false
cache: packages
r_binary_packages:
  - gsl