# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

warnings_are_errors: false
addons:
  apt:
    packages:
    - libcurl4-openssl-dev
    - libgsl0-dev
before_install:
  - cd code
language: R
sudo: false
cache: packages
r_binary_packages:
  - gsl

r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'