# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.f.optim.mat <- function(alpha, lambda, nu, zeta, Cmat, Z, n, p, D, idsel, G, H, y, x, yty, Zpres) {
    .Call(`_NIG_f_optim_mat`, alpha, lambda, nu, zeta, Cmat, Z, n, p, D, idsel, G, H, y, x, yty, Zpres)
}

.f.optim.list <- function(alpha, lambda, nu, zeta, Cmat, Z, n, p, D, G, H, y, x, yty, Zpres) {
    .Call(`_NIG_f_optim_list`, alpha, lambda, nu, zeta, Cmat, Z, n, p, D, G, H, y, x, yty, Zpres)
}

.Sigma.unp <- function(aold, bold, xu, xr, u, r) {
    .Call(`_NIG_Sigma_unp`, aold, bold, xu, xr, u, r)
}

.Sigma <- function(aold, bold, x) {
    .Call(`_NIG_Sigma`, aold, bold, x)
}

.aux.var.unp <- function(aold, bold, y, xu, xr, u, r) {
    .Call(`_NIG_aux_var_unp`, aold, bold, y, xu, xr, u, r)
}

.aux.var <- function(aold, bold, y, x, ytx) {
    .Call(`_NIG_aux_var`, aold, bold, y, x, ytx)
}

