# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ratio_besselK_cpp <- function(x, nu) {
    .Call(`_cambridge_ratio_besselK_cpp`, x, nu)
}

vb_update_cpp <- function(zetaold, aold, lambda, theta, x, xxt, xtx, y) {
    .Call(`_cambridge_vb_update_cpp`, zetaold, aold, lambda, theta, x, xxt, xtx, y)
}

VarOneIter <- function(myy, myX, myP, aRand, bRand, bRandStarInit, dSigmaStarInit, cSigma, dSigma, lincomb) {
    .Call(`_cambridge_VarOneIter`, myy, myX, myP, aRand, bRand, bRandStarInit, dSigmaStarInit, cSigma, dSigma, lincomb)
}

fixedPointIterEB <- function(initab, myallaRandStar, myallbRandStar, mymaxiter, myeps) {
    .Call(`_cambridge_fixedPointIterEB`, initab, myallaRandStar, myallbRandStar, mymaxiter, myeps)
}

BSEMVarOneIter <- function(ylist, Xlist, Plist, alist, blist, bstarlist, cSigma, dSigma, dstarvec, lincomblist) {
    .Call(`_cambridge_BSEMVarOneIter`, ylist, Xlist, Plist, alist, blist, bstarlist, cSigma, dSigma, dstarvec, lincomblist)
}

