# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ratio_besselK <- function(x, nu) {
    .Call(`_cambridge_ratio_besselK`, x, nu)
}

